import { defineField, defineType } from "sanity";

export const homePage = defineType({
  name: "homePage", title: "Home Page", type: "document",
  fields: [
    defineField({ name: "seo", title: "Search and sharing", type: "seo", validation: (rule) => rule.required() }),
    defineField({ name: "hero", title: "Hero", type: "hero", validation: (rule) => rule.required() }),
    defineField({ name: "heroNote", title: "Hero note", type: "string", validation: (rule) => rule.required().max(100) }),
    defineField({ name: "primaryCta", title: "Primary hero link", type: "callToAction", validation: (rule) => rule.required() }),
    defineField({ name: "secondaryCta", title: "Secondary hero link", type: "callToAction", validation: (rule) => rule.required() }),
    defineField({ name: "serviceEyebrow", title: "Service section eyebrow", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "serviceTitle", title: "Service section heading", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "serviceDescription", title: "Service section description", type: "text", rows: 2, validation: (rule) => rule.required() }),
    defineField({ name: "serviceCards", title: "Service cards", type: "array", validation: (rule) => rule.required().length(3), of: [{ type: "object", fields: [
      defineField({ name: "kind", title: "Icon", type: "string", options: { list: ["worship", "location", "fellowship"] }, validation: (rule) => rule.required() }),
      defineField({ name: "title", title: "Title", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "value", title: "Main value", type: "string", description: "Use {serviceTime} to insert the seasonal worship time.", validation: (rule) => rule.required() }),
      defineField({ name: "description", title: "Description", type: "text", rows: 2, validation: (rule) => rule.required() }),
    ], preview: { select: { title: "title", subtitle: "value" } } }] }),
    defineField({ name: "seasonalNote", title: "Seasonal schedule note", type: "text", rows: 2, validation: (rule) => rule.required() }),
    defineField({ name: "leadershipEyebrow", title: "Leadership eyebrow", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "leadershipTitle", title: "Leadership heading", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "leadershipDescription", title: "Leadership description", type: "text", rows: 2, validation: (rule) => rule.required() }),
    defineField({ name: "trusteesTitle", title: "Trustees heading", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "trusteesDescription", title: "Trustees description", type: "text", rows: 2, validation: (rule) => rule.required() }),
    defineField({ name: "objectivesEyebrow", title: "Objectives eyebrow", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "objectivesTitle", title: "Objectives heading", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "objectivesDescription", title: "Objectives description", type: "text", rows: 2, validation: (rule) => rule.required() }),
    defineField({ name: "storyEyebrow", title: "Story eyebrow", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "storyTitle", title: "Story heading", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "storyBody", title: "Story text", type: "richText", validation: (rule) => rule.required().min(1) }),
    defineField({ name: "storyImage", title: "Story image", type: "image", options: { hotspot: true }, validation: (rule) => rule.required(), fields: [{ name: "alt", title: "Alternative text", type: "string", validation: (rule) => rule.required() }] }),
    defineField({ name: "storyCta", title: "Story link", type: "callToAction", validation: (rule) => rule.required() }),
    defineField({ name: "eventsEyebrow", title: "Events eyebrow", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "eventsTitle", title: "Events heading", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "eventsCta", title: "Events link", type: "callToAction", validation: (rule) => rule.required() }),
  ],
  preview: { prepare: () => ({ title: "Home Page", subtitle: "Editable website copy" }) },
});
