export const contentQuery = String.raw`{
  "settings": *[_id == "siteSettings"][0]{name, shortName, domain, description, email, phoneDisplay, phoneHref, venue, address, region, mapEmbedUrl, footerDescription, serviceTime},
  "pages": {
    "home": *[_id == "homePage"][0]{..., hero{eyebrow,title,description,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},"storyImage":storyImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}, seo{title,description,"socialImage":socialImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}}},
    "about": *[_id == "aboutPage"][0]{..., hero{eyebrow,title,description,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},"historyImage":historyImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt},founders{...,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},seo{title,description,"socialImage":socialImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}}},
    "events": *[_id == "eventsPage"][0]{..., hero{eyebrow,title,description,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},seo{title,description,"socialImage":socialImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}}},
    "gallery": *[_id == "galleryPage"][0]{..., hero{eyebrow,title,description,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},seo{title,description,"socialImage":socialImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}}},
    "giving": *[_id == "givingPage"][0]{..., hero{eyebrow,title,description,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},seo{title,description,"socialImage":socialImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}}},
    "contact": *[_id == "contactPage"][0]{..., hero{eyebrow,title,description,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}},seo{title,description,"socialImage":socialImage{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt}}}
  },
  "events": *[_type == "event"] | order(order asc){"id":stableId.current,title,dateLabel,timeKind,timeLabel,location,description,recurring,"month":calendarDate.month,"day":calendarDate.day,"year":calendarDate.year,order},
  "people": *[_type == "person"] | order(group asc, order asc){"id":stableId.current,name,role,category,bio,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt},group,order},
  "ministries": *[_type == "ministry"] | order(order asc){"id":stableId.current,name,icon,"leaderId":leader->stableId.current,members,order},
  "objectives": *[_type == "objective"] | order(order asc){"id":stableId.current,icon,shortTitle,shortDescription,title,description,order},
  "gallery": *[_type == "galleryPhoto"] | order(order asc){"id":stableId.current,title,caption,"image":image{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt},category,dateLabel,order},
  "givingMethods": *[_type == "givingMethod"] | order(order asc){"id":stableId.current,name,description,contact,"qrCode":qrCode{"source":"sanity","url":asset->url,"width":asset->metadata.dimensions.width,"height":asset->metadata.dimensions.height,"lqip":asset->metadata.lqip,"alt":alt},brandColor,instructions,order},
  "impactAreas": *[_type == "impactArea"] | order(order asc){"id":stableId.current,icon,title,description,order}
}`;
